version: "3"

services:
  mongo:
    image: mongo
    container_name: mongo-bookstore
    ports:
      - "27017:27017"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: express-bookstore
    command: npm run dev
    volumes:
      - ./backend/src:/app/src
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - app-network
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-bookstore
    command: npm run dev --host
    volumes:
      - ./frontend/src:/app/src
    ports:
      - "5173:8000"
    networks:
      - app-network
    env_file:
      - .env

networks:
  app-network:
    driver: bridge
